name: Deploy to GHPages

on:
  push:
    branches: [ "Publish" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Swift
        uses: sersoft-gmbh/swifty-linux-action@v1
        with:
          release-version: 5.6.2

      - name: Install Publish
        run: |
          git clone https://github.com/JohnSundell/Publish.git
          cd Publish
          make

      - uses: actions/checkout@v3

      - name: Generate site
        run: |
          cd $GITHUB_WORKSPACE/blog/
          publish generate

      - name: Publish site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: blog/Output
